language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"
    - "nightly"

env:
 matrix:
    include:
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    allow_failures:
    - python: "2.7"
    - python: "3.7-dev"
    - python: "nightly"

install:
    - "python -m pip install --upgrade setuptools pip"
    - "python -m pip install pytest coverage pytest-cov coveralls[yaml] x86cpu numpy cython"

script:
    - "py.test -v --cov=compilertools --cov-report=term-missing"

after_success:
    - "coveralls"
