language: python

python:
    - "3.8"
    - "3.7"
    - "3.6"
    - "3.5"

matrix:
  include:
    # LLVM Clang on Linux
    - compiler: clang
      python: "3.8"

    # Apple MacOS
    - os: osx
      language: sh  # Python not directly available as language
      sudo: true
      python: "3.6"
      before_install:
      - python3 -V  # Print system version

sudo: true

install:
    - "python3 -m pip install --upgrade --upgrade-strategy=eager setuptools pip wheel"
    - "python3 -m pip install --upgrade --upgrade-strategy=eager pytest coverage pytest-cov codecov x86cpu numpy cython"

script:
    - "pytest -v --cov=compilertools --cov-report=term-missing"

after_success:
    - "codecov"
