environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python36-x86"

build: off

test_script:
  - "python -m pip install pytest coverage"
  - "py.test -v --cov=compilertools --cov-report=term-missing"
