environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python36"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

test_script:
  - "python -m pip install pytest coverage pytest-cov x86cpu"
  - "py.test -v --cov=compilertools --cov-report=term-missing"
